###EXPERIMENT 2 : Numerical Python

##NORMALIZATION PROBLEM : Create a random 5 x 5 ndarray

In [6]:
import numpy as np

In [34]:
#creating a random 5x5 ndarray
X = np.random.rand(5,5)

#original array
print ("Original Array (X):\n", X)

#.mean and .std calls
mean_X = X.mean()
std_X = X.std()

#normalization expression
X_normalized = (X- mean_X) / std_X

#normalize the array
print("\nNormalized Array (X_normalized):\n", X_normalized)

#save noramlized ndarray as npy
np.save('X_normalized.npy', X_normalized)


Original Array (X):
 [[0.48242637 0.01899672 0.27035104 0.68740754 0.46035445]
 [0.85278891 0.87202177 0.73196376 0.87433232 0.5401713 ]
 [0.71208084 0.12668069 0.5115928  0.82446044 0.90178258]
 [0.16487145 0.34914121 0.38636166 0.28939231 0.38894661]
 [0.33788983 0.26176371 0.46271184 0.45388911 0.31734151]]

Normalized Array (X_normalized):
 [[-0.03515303 -1.89432786 -0.88595122  0.78718505 -0.12370055]
 [ 1.45065765  1.52781554  0.96593452  1.53708493  0.19650658]
 [ 0.88616874 -1.46232413  0.0818561   1.33701026  1.64720916]
 [-1.30911145 -0.5698629  -0.42054288 -0.80956197 -0.41017266]
 [-0.6150009  -0.92040164 -0.11424323 -0.14963802 -0.69743608]]


##DIVISIBLE BY 3 PROBLEM : Create a 10x10 ndarray

In [11]:
import numpy as np

#creating a 10x10 ndarray with squares of first 100 positive integers
A = np.arange (1, 101)**2

#reshaping array into 10x10
A = A.reshape ((10,10))

#original 10x10 array
print ("10 x 10 Array (A):\n", A)

#finding elements divisible by 3
div_by_3 = A[A % 3 == 0]

#elements divisible by 3
print ("\nElements divisible by 3 (div_by_3):\n", div_by_3)

#saving elements into npy file
np.save('div_by_3.npy', div_by_3)

10 x 10 Array (A):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3 (div_by_3):
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
